services:
  - type: static
    name: smarthome-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://smarthomeapplianceshub-backend.onrender.com
      - key: VITE_ADMIN_API_URL
        value: https://smarthomeapplianceshub-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
